spring.main.web-application-type=NONE
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://34.121.248.216/bir-solo-loans?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.show-sql=false
amazonProperties.bucketName=test
amazonProperties.region=us-east-1
##CLOUD-SQL-CONFIGURATIONS
spring.cloud.gcp.sql.database-name=[DATABASE NAME]
spring.cloud.gcp.sql.instance-connection-name=[INSTANCE   CONNECTION NAME]
  # So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
  # Enforces database initialization
spring.datasource.initialization-mode=always
spring.datasource.username=[USERNAME]
spring.datasource.password=[Password]
spring.cloud.gcp.project-id=[PROJECT_ID]
spring.cloud.gcp.credentials.location=[PATH FOR THE JSON FILE]